version: '3.8'
services:
  db:
    image: postgres
    restart: always
    ports:
      - "35432:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  api:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/db
    ports:
      - "3000:3000"
    # volumes:
    #   - .:/app/
    #   - /app/node_modules
