version: '3.8'
services:
  db:
    build: ./db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'

  api:
    build: ./api
    depends_on:
      - db
      - redis
    environment:
      PGHOST: db
      PGDATABASE: ${POSTGRES_DB}
      PGUSER: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '3000:3000'
    volumes:
      - ./api/src:/app/src
      - ./api/node_modules:/app/node_modules
